/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelproject;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;

/**
 *
 * @author Kuba
 */
public class GUI extends javax.swing.JFrame {

    String typPokoje;
    String cena;
    String[] odDatum, doDatum;
    List<Pokoje> listPokoju;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setAllInvisible();
        invokeFirstFloor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        checkOutTextField = new javax.swing.JTextField();
        checkInTextField = new javax.swing.JTextField();
        hledejPokojeButton = new javax.swing.JButton();
        typPokojeCombo = new javax.swing.JComboBox();
        nextButton = new javax.swing.JButton();
        nextButton2 = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        backButton2 = new javax.swing.JButton();
        backButton3 = new javax.swing.JButton();
        backButton4 = new javax.swing.JButton();
        pocetTriple = new javax.swing.JLabel();
        pocetDouble = new javax.swing.JLabel();
        pocetSingle = new javax.swing.JLabel();
        trippleRadioButton = new javax.swing.JRadioButton();
        doubleRadioButton = new javax.swing.JRadioButton();
        singleRadioButton = new javax.swing.JRadioButton();
        prijmeniLabel = new javax.swing.JTextField();
        jmenoLabel = new javax.swing.JTextField();
        mestoLabel = new javax.swing.JTextField();
        statLabel = new javax.swing.JTextField();
        uliceLabel = new javax.swing.JTextField();
        cpLabel = new javax.swing.JTextField();
        pscLabel = new javax.swing.JTextField();
        telefonLabel = new javax.swing.JTextField();
        emailLabel = new javax.swing.JTextField();
        obchLabel = new javax.swing.JTextField();
        dicLabel = new javax.swing.JTextField();
        icLabel = new javax.swing.JTextField();
        cenaTriple = new javax.swing.JLabel();
        cenaDouble = new javax.swing.JLabel();
        cenaSingle = new javax.swing.JLabel();
        scrollPanel1 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        scrollPanel = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        bgImageLabel = new javax.swing.JLabel();
        bg2ImageLabel = new javax.swing.JLabel();
        bg3ImageLabel = new javax.swing.JLabel();
        bg4ImageLabel = new javax.swing.JLabel();
        bg5ImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1071, 662));
        setMinimumSize(new java.awt.Dimension(1071, 662));
        setPreferredSize(new java.awt.Dimension(1071, 662));
        setResizable(false);
        getContentPane().setLayout(null);

        checkOutTextField.setBackground(new java.awt.Color(43, 58, 63));
        checkOutTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        checkOutTextField.setForeground(new java.awt.Color(255, 255, 255));
        checkOutTextField.setText("DD/MM/YYYY");
        checkOutTextField.setBorder(null);
        checkOutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(checkOutTextField);
        checkOutTextField.setBounds(715, 302, 150, 30);

        checkInTextField.setBackground(new java.awt.Color(43, 58, 63));
        checkInTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        checkInTextField.setForeground(new java.awt.Color(255, 255, 255));
        checkInTextField.setText("DD/MM/YYYY");
        checkInTextField.setBorder(null);
        getContentPane().add(checkInTextField);
        checkInTextField.setBounds(715, 237, 150, 30);

        hledejPokojeButton.setBorder(null);
        hledejPokojeButton.setContentAreaFilled(false);
        hledejPokojeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hledejPokojeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hledejPokojeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hledejPokojeButton);
        hledejPokojeButton.setBounds(685, 485, 240, 90);

        typPokojeCombo.setBackground(new java.awt.Color(43, 58, 63));
        typPokojeCombo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        typPokojeCombo.setForeground(new java.awt.Color(255, 255, 255));
        typPokojeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SINGLE", "DOUBLE", "TRIPPLE" }));
        typPokojeCombo.setBorder(null);
        typPokojeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typPokojeComboActionPerformed(evt);
            }
        });
        getContentPane().add(typPokojeCombo);
        typPokojeCombo.setBounds(700, 400, 210, 40);

        nextButton.setBorder(null);
        nextButton.setContentAreaFilled(false);
        nextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton);
        nextButton.setBounds(540, 370, 120, 40);

        nextButton2.setBorder(null);
        nextButton2.setContentAreaFilled(false);
        nextButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton2);
        nextButton2.setBounds(770, 370, 120, 40);

        finishButton.setBorder(null);
        finishButton.setContentAreaFilled(false);
        finishButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });
        getContentPane().add(finishButton);
        finishButton.setBounds(770, 370, 120, 40);

        backButton2.setBorder(null);
        backButton2.setContentAreaFilled(false);
        backButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(backButton2);
        backButton2.setBounds(180, 370, 120, 40);

        backButton3.setBorder(null);
        backButton3.setContentAreaFilled(false);
        backButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(backButton3);
        backButton3.setBounds(180, 370, 120, 40);

        backButton4.setBorder(null);
        backButton4.setContentAreaFilled(false);
        backButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(backButton4);
        backButton4.setBounds(180, 370, 120, 40);

        pocetTriple.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pocetTriple.setForeground(new java.awt.Color(255, 51, 51));
        pocetTriple.setText("0");
        getContentPane().add(pocetTriple);
        pocetTriple.setBounds(564, 323, 34, 20);

        pocetDouble.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pocetDouble.setForeground(new java.awt.Color(255, 51, 51));
        pocetDouble.setText("0");
        getContentPane().add(pocetDouble);
        pocetDouble.setBounds(440, 323, 30, 20);

        pocetSingle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pocetSingle.setForeground(new java.awt.Color(255, 51, 51));
        pocetSingle.setText("0");
        getContentPane().add(pocetSingle);
        pocetSingle.setBounds(320, 323, 34, 20);

        buttonGroup1.add(trippleRadioButton);
        trippleRadioButton.setBorder(null);
        trippleRadioButton.setContentAreaFilled(false);
        trippleRadioButton.setEnabled(false);
        getContentPane().add(trippleRadioButton);
        trippleRadioButton.setBounds(487, 322, 40, 23);

        buttonGroup1.add(doubleRadioButton);
        doubleRadioButton.setBorder(null);
        doubleRadioButton.setContentAreaFilled(false);
        doubleRadioButton.setEnabled(false);
        getContentPane().add(doubleRadioButton);
        doubleRadioButton.setBounds(364, 322, 40, 23);

        buttonGroup1.add(singleRadioButton);
        singleRadioButton.setBorder(null);
        singleRadioButton.setContentAreaFilled(false);
        singleRadioButton.setEnabled(false);
        getContentPane().add(singleRadioButton);
        singleRadioButton.setBounds(240, 322, 40, 23);

        prijmeniLabel.setBackground(new java.awt.Color(69, 79, 89));
        prijmeniLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        prijmeniLabel.setForeground(new java.awt.Color(255, 255, 255));
        prijmeniLabel.setBorder(null);
        getContentPane().add(prijmeniLabel);
        prijmeniLabel.setBounds(392, 168, 140, 20);

        jmenoLabel.setBackground(new java.awt.Color(69, 79, 89));
        jmenoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jmenoLabel.setForeground(new java.awt.Color(255, 255, 255));
        jmenoLabel.setBorder(null);
        getContentPane().add(jmenoLabel);
        jmenoLabel.setBounds(232, 168, 130, 20);

        mestoLabel.setBackground(new java.awt.Color(69, 79, 89));
        mestoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mestoLabel.setForeground(new java.awt.Color(255, 255, 255));
        mestoLabel.setBorder(null);
        getContentPane().add(mestoLabel);
        mestoLabel.setBounds(392, 211, 140, 20);

        statLabel.setBackground(new java.awt.Color(69, 79, 89));
        statLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        statLabel.setForeground(new java.awt.Color(255, 255, 255));
        statLabel.setBorder(null);
        statLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(statLabel);
        statLabel.setBounds(232, 211, 130, 20);

        uliceLabel.setBackground(new java.awt.Color(69, 79, 89));
        uliceLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        uliceLabel.setForeground(new java.awt.Color(255, 255, 255));
        uliceLabel.setBorder(null);
        getContentPane().add(uliceLabel);
        uliceLabel.setBounds(232, 254, 180, 20);

        cpLabel.setBackground(new java.awt.Color(69, 79, 89));
        cpLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cpLabel.setForeground(new java.awt.Color(255, 255, 255));
        cpLabel.setBorder(null);
        getContentPane().add(cpLabel);
        cpLabel.setBounds(438, 254, 80, 20);

        pscLabel.setBackground(new java.awt.Color(69, 79, 89));
        pscLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pscLabel.setForeground(new java.awt.Color(255, 255, 255));
        pscLabel.setBorder(null);
        getContentPane().add(pscLabel);
        pscLabel.setBounds(438, 291, 80, 20);

        telefonLabel.setBackground(new java.awt.Color(69, 79, 89));
        telefonLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        telefonLabel.setForeground(new java.awt.Color(255, 255, 255));
        telefonLabel.setBorder(null);
        getContentPane().add(telefonLabel);
        telefonLabel.setBounds(232, 332, 130, 20);

        emailLabel.setBackground(new java.awt.Color(69, 79, 89));
        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setBorder(null);
        getContentPane().add(emailLabel);
        emailLabel.setBounds(392, 332, 140, 20);

        obchLabel.setBackground(new java.awt.Color(69, 79, 89));
        obchLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        obchLabel.setForeground(new java.awt.Color(255, 255, 255));
        obchLabel.setBorder(null);
        getContentPane().add(obchLabel);
        obchLabel.setBounds(635, 168, 170, 20);

        dicLabel.setBackground(new java.awt.Color(69, 79, 89));
        dicLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dicLabel.setForeground(new java.awt.Color(255, 255, 255));
        dicLabel.setBorder(null);
        getContentPane().add(dicLabel);
        dicLabel.setBounds(635, 211, 130, 20);

        icLabel.setBackground(new java.awt.Color(69, 79, 89));
        icLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        icLabel.setForeground(new java.awt.Color(255, 255, 255));
        icLabel.setBorder(null);
        getContentPane().add(icLabel);
        icLabel.setBounds(635, 254, 130, 20);

        cenaTriple.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cenaTriple.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cenaTriple.setText("0 ,-");
        getContentPane().add(cenaTriple);
        cenaTriple.setBounds(494, 293, 60, 20);

        cenaDouble.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cenaDouble.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cenaDouble.setText("0 ,-");
        getContentPane().add(cenaDouble);
        cenaDouble.setBounds(376, 293, 50, 20);

        cenaSingle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cenaSingle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cenaSingle.setText("0 ,-");
        getContentPane().add(cenaSingle);
        cenaSingle.setBounds(244, 293, 60, 20);

        scrollPanel1.setBackground(new java.awt.Color(71, 79, 89));
        scrollPanel1.setBorder(null);
        scrollPanel1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textArea1.setBackground(new java.awt.Color(71, 79, 89));
        textArea1.setColumns(20);
        textArea1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        textArea1.setForeground(new java.awt.Color(255, 255, 255));
        textArea1.setRows(5);
        textArea1.setBorder(null);
        textArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textArea1.setFocusable(false);
        scrollPanel1.setViewportView(textArea1);

        getContentPane().add(scrollPanel1);
        scrollPanel1.setBounds(550, 170, 310, 200);

        scrollPanel.setBackground(new java.awt.Color(71, 79, 89));
        scrollPanel.setBorder(null);
        scrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textArea.setBackground(new java.awt.Color(71, 79, 89));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        textArea.setForeground(new java.awt.Color(255, 255, 255));
        textArea.setRows(5);
        textArea.setBorder(null);
        textArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textArea.setFocusable(false);
        scrollPanel.setViewportView(textArea);

        getContentPane().add(scrollPanel);
        scrollPanel.setBounds(230, 170, 320, 200);

        bgImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/obrazek1.png"))); // NOI18N
        getContentPane().add(bgImageLabel);
        bgImageLabel.setBounds(0, 0, 1109, 662);

        bg2ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/obrazek2.png"))); // NOI18N
        getContentPane().add(bg2ImageLabel);
        bg2ImageLabel.setBounds(0, 0, 1109, 662);

        bg3ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/obrazek3.png"))); // NOI18N
        getContentPane().add(bg3ImageLabel);
        bg3ImageLabel.setBounds(0, 0, 1109, 662);

        bg4ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/obrazek4.png"))); // NOI18N
        getContentPane().add(bg4ImageLabel);
        bg4ImageLabel.setBounds(0, 0, 1109, 662);

        bg5ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/obrazek5.png"))); // NOI18N
        getContentPane().add(bg5ImageLabel);
        bg5ImageLabel.setBounds(0, 0, 1109, 662);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkOutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutTextFieldActionPerformed

    private void hledejPokojeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hledejPokojeButtonActionPerformed
        setAllInvisible();
        invokeSecondFloor();
        String[] checkInDate;
        String[] checkOutDate;
        checkInDate = checkInTextField.getText().split("/");
        checkOutDate = checkOutTextField.getText().split("/");

        if (checkInDate.length == 3 && checkOutDate.length == 3) {
            for (int i = 0; i < 3; i++) {
                if (!isNumber(checkInDate[i]) || !isNumber(checkOutDate[i])) {
                    checkInTextField.setText("DD/MM/YYYY");
                    checkOutTextField.setText("DD/MM/YYYY");
                    nextButton.setVisible(false);
                    return;
                }
                System.out.println("jsou to cisla");
            }
        } else {
            checkInTextField.setText("DD/MM/YYYY");
            checkOutTextField.setText("DD/MM/YYYY");
            nextButton.setVisible(false);
            return;
        }

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("HotelProjectPU");
        EntityManager em = emf.createEntityManager();;
        //em.getTransaction().begin();

        List<Pokoje> listPokoju = null;
        Query queryPokoje;
        switch (typPokojeCombo.getSelectedIndex()) {
            case 0:
                queryPokoje = em.createNamedQuery("Pokoje.findByPocetLuzek");
                queryPokoje.setParameter("pocetLuzek", 1);
                listPokoju = queryPokoje.getResultList();
                singleRadioButton.setSelected(true);
                typPokoje = "single";
                cena = "720 ,-";
                break;
            case 1:
                queryPokoje = em.createNamedQuery("Pokoje.findByPocetLuzek");
                queryPokoje.setParameter("pocetLuzek", 2);
                listPokoju = queryPokoje.getResultList();
                doubleRadioButton.setSelected(true);
                typPokoje = "double";
                cena = "1250 ,-";
                break;
            case 2:
                queryPokoje = em.createNamedQuery("Pokoje.findByPocetLuzek");
                queryPokoje.setParameter("pocetLuzek", 3);
                listPokoju = queryPokoje.getResultList();
                trippleRadioButton.setSelected(true);
                typPokoje = "triple";
                cena = "2250 ,-";
                break;
        }

        Query queryRezervace = em.createNamedQuery("Rezervace.findAll");
        List<Rezervace> listRezervaci = queryRezervace.getResultList();

        for (int j = 0; j < listRezervaci.size(); j++) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date prijezd = null;
            Date odjezd = null;
            try {
                prijezd = sdf.parse(checkInDate[2] + "-" + checkInDate[1] + "-" + checkInDate[0]);
                odjezd = sdf.parse(checkOutDate[2] + "-" + checkOutDate[1] + "-" + checkOutDate[0]);
            } catch (ParseException ex) {
                System.err.println("Can't process this date.");
            }

            if (prijezd.before(listRezervaci.get(j).getDatumDo()) && prijezd.after(listRezervaci.get(j).getDatumOd())) {
                for (int i = 0; i < listRezervaci.get(j).getPokojeCollection().size(); i++) {
                    Iterator<Pokoje> it = listRezervaci.get(j).getPokojeCollection().iterator();
                    while (it.hasNext()) {
                        Pokoje tmp = it.next();
                        if (listPokoju.contains(tmp)) {
                            System.out.println("mažu pokoj: " + tmp.toString());
                            listPokoju.remove(tmp);
                        }
                    }
                }
            }
            if (odjezd.before(listRezervaci.get(j).getDatumDo()) && odjezd.after(listRezervaci.get(j).getDatumOd())) {
                for (int i = 0; i < listRezervaci.get(j).getPokojeCollection().size(); i++) {
                    Iterator<Pokoje> it = listRezervaci.get(j).getPokojeCollection().iterator();
                    while (it.hasNext()) {
                        Pokoje tmp = it.next();
                        if (listPokoju.contains(tmp)) {
                            System.out.println("mažu pokoj: " + tmp.toString());
                            listPokoju.remove(tmp);
                        }
                    }
                }
            }

        }

        System.out.println("vypis pokoju: ");
        for (int i = 0; i < listPokoju.size(); i++) {
            System.out.println(listPokoju.get(i).toString());
        }

        this.listPokoju = listPokoju;

        pocetSingle.setText("?");
        pocetDouble.setText("?");
        pocetTriple.setText("?");

        switch (typPokoje) {
            case "single":
                pocetSingle.setText(String.valueOf(listPokoju.size()));
                break;
            case "double":
                pocetDouble.setText(String.valueOf(listPokoju.size()));
                break;
            case "triple":
                pocetTriple.setText(String.valueOf(listPokoju.size()));
                break;
        }

        cenaSingle.setText("720 ,-");
        cenaDouble.setText("1250 ,-");
        cenaTriple.setText("2250 ,-");

        odDatum = checkInDate;
        doDatum = checkOutDate;

        if ("0".equals(pocetSingle.getText()) || "0".equals(pocetDouble.getText()) || "0".equals(pocetTriple.getText())) {
            nextButton.setVisible(false);
        }
    }//GEN-LAST:event_hledejPokojeButtonActionPerformed

    private boolean isNumber(String s) {
        try {
            int c = Integer.parseInt(s);

        } catch (NumberFormatException e) {
            return false;
        }
        return true;
    }
    private void typPokojeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typPokojeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typPokojeComboActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        setAllInvisible();
        invokeThirdFloor();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void nextButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton2ActionPerformed
        setAllInvisible();
        if (vyplneno()) {
            textArea.setText("Jméno: \n" + jmenoLabel.getText() + " "
                    + prijmeniLabel.getText() + "\n\n"
                    + "Adresa: \n" + statLabel.getText() + ", "
                    + mestoLabel.getText() + "\n"
                    + uliceLabel.getText() + " " + cpLabel.getText() + " " + pscLabel.getText() + "\n\n"
                    + "tel: " + telefonLabel.getText() + ", e-mail: " + emailLabel.getText()
                    + "\n\n"
                    + "Obchodní jméno/název firmy: \n" + obchLabel.getText() + "\n"
                    + icLabel.getText() + ", " + dicLabel.getText()
            );
            textArea1.setText("Pokoj: \n" + typPokoje + "\n\n"
                    + "Cena: \n" + cena + " / noc \n"
                    + "\n\n"
                    + "Období: \n"
                    + "od: " + odDatum[0] + "." + odDatum[1] + "." + odDatum[2] + " - "
                    + "do: " + doDatum[0] + "." + doDatum[1] + "." + doDatum[2]
            );

            if ("".equals(obchLabel.getText())) {
                obchLabel = null;
            }
            if ("".equals(icLabel.getText())) {
                icLabel = null;
            }
            if ("".equals(dicLabel.getText())) {
                dicLabel = null;
            }
            invokeFourthFloor();
        } else {
            invokeThirdFloor();
        }
    }//GEN-LAST:event_nextButton2ActionPerformed

    private boolean vyplneno() {
        return !"".equals(jmenoLabel.getText()) && !"".equals(prijmeniLabel.getText()) && !"".equals(mestoLabel.getText())
                && !"".equals(statLabel.getText()) && !"".equals(uliceLabel.getText()) && !"".equals(cpLabel.getText())
                && !"".equals(pscLabel.getText()) && !"".equals(emailLabel.getText());
    }

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed
        setAllInvisible();
        invokeSecondFloor();
    }//GEN-LAST:event_backButton2ActionPerformed

    private void backButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton3ActionPerformed
        setAllInvisible();
        invokeThirdFloor();
    }//GEN-LAST:event_backButton3ActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        setAllInvisible();
        //tady transakcí všechno poslat do databáze
        
        
        invokeFifthFloor();
    }//GEN-LAST:event_finishButtonActionPerformed

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        setAllInvisible();
        invokeFirstFloor();
    }//GEN-LAST:event_backButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton2;
    private javax.swing.JButton backButton3;
    private javax.swing.JButton backButton4;
    private javax.swing.JLabel bg2ImageLabel;
    private javax.swing.JLabel bg3ImageLabel;
    private javax.swing.JLabel bg4ImageLabel;
    private javax.swing.JLabel bg5ImageLabel;
    private javax.swing.JLabel bgImageLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cenaDouble;
    private javax.swing.JLabel cenaSingle;
    private javax.swing.JLabel cenaTriple;
    private javax.swing.JTextField checkInTextField;
    private javax.swing.JTextField checkOutTextField;
    private javax.swing.JTextField cpLabel;
    private javax.swing.JTextField dicLabel;
    private javax.swing.JRadioButton doubleRadioButton;
    private javax.swing.JTextField emailLabel;
    private javax.swing.JButton finishButton;
    private javax.swing.JButton hledejPokojeButton;
    private javax.swing.JTextField icLabel;
    private javax.swing.JTextField jmenoLabel;
    private javax.swing.JTextField mestoLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton nextButton2;
    private javax.swing.JTextField obchLabel;
    private javax.swing.JLabel pocetDouble;
    private javax.swing.JLabel pocetSingle;
    private javax.swing.JLabel pocetTriple;
    private javax.swing.JTextField prijmeniLabel;
    private javax.swing.JTextField pscLabel;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JScrollPane scrollPanel1;
    private javax.swing.JRadioButton singleRadioButton;
    private javax.swing.JTextField statLabel;
    private javax.swing.JTextField telefonLabel;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextArea textArea1;
    private javax.swing.JRadioButton trippleRadioButton;
    private javax.swing.JComboBox typPokojeCombo;
    private javax.swing.JTextField uliceLabel;
    // End of variables declaration//GEN-END:variables

    private void setAllInvisible() {
        singleRadioButton.setVisible(false);
        doubleRadioButton.setVisible(false);
        trippleRadioButton.setVisible(false);

        nextButton.setVisible(false);
        nextButton2.setVisible(false);
        backButton2.setVisible(false);
        backButton3.setVisible(false);
        backButton4.setVisible(false);
        finishButton.setVisible(false);

        checkInTextField.setVisible(false);
        checkOutTextField.setVisible(false);

        bg2ImageLabel.setVisible(false);
        bg3ImageLabel.setVisible(false);
        bg4ImageLabel.setVisible(false);
        bg5ImageLabel.setVisible(false);
        bgImageLabel.setVisible(false);

        pocetSingle.setVisible(false);
        pocetDouble.setVisible(false);
        pocetTriple.setVisible(false);
        cenaSingle.setVisible(false);
        cenaDouble.setVisible(false);
        cenaTriple.setVisible(false);

        prijmeniLabel.setVisible(false);
        jmenoLabel.setVisible(false);
        mestoLabel.setVisible(false);
        statLabel.setVisible(false);
        uliceLabel.setVisible(false);
        cpLabel.setVisible(false);
        pscLabel.setVisible(false);
        telefonLabel.setVisible(false);
        emailLabel.setVisible(false);
        obchLabel.setVisible(false);
        icLabel.setVisible(false);
        dicLabel.setVisible(false);

        textArea.setVisible(false);
        textArea1.setVisible(false);
        scrollPanel.setVisible(false);
        scrollPanel1.setVisible(false);

        hledejPokojeButton.setVisible(false);
        typPokojeCombo.setVisible(false);
    }

    private void invokeFirstFloor() {
        bgImageLabel.setVisible(true);
        checkInTextField.setVisible(true);
        checkOutTextField.setVisible(true);
        typPokojeCombo.setVisible(true);
        hledejPokojeButton.setVisible(true);
    }

    private void invokeSecondFloor() {
        bg2ImageLabel.setVisible(true);
        checkInTextField.setVisible(true);
        checkOutTextField.setVisible(true);
        typPokojeCombo.setVisible(true);
        hledejPokojeButton.setVisible(true);
        singleRadioButton.setVisible(true);
        doubleRadioButton.setVisible(true);
        trippleRadioButton.setVisible(true);
        nextButton.setVisible(true);
        pocetSingle.setVisible(true);
        pocetDouble.setVisible(true);
        pocetTriple.setVisible(true);
        cenaSingle.setVisible(true);
        cenaDouble.setVisible(true);
        cenaTriple.setVisible(true);

    }

    private void invokeThirdFloor() {
        bg3ImageLabel.setVisible(true);
        nextButton2.setVisible(true);
        backButton2.setVisible(true);
        prijmeniLabel.setVisible(true);
        jmenoLabel.setVisible(true);
        statLabel.setVisible(true);
        mestoLabel.setVisible(true);
        uliceLabel.setVisible(true);
        cpLabel.setVisible(true);
        pscLabel.setVisible(true);
        telefonLabel.setVisible(true);
        emailLabel.setVisible(true);
        obchLabel.setVisible(true);
        icLabel.setVisible(true);
        dicLabel.setVisible(true);
    }

    private void invokeFourthFloor() {
        bg4ImageLabel.setVisible(true);
        backButton3.setVisible(true);
        finishButton.setVisible(true);
        textArea.setVisible(true);
        textArea1.setVisible(true);
        scrollPanel.setVisible(true);
        scrollPanel1.setVisible(true);
    }

    private void invokeFifthFloor() {
        bg5ImageLabel.setVisible(true);
        backButton4.setVisible(true);

    }
}
